import { EthereumMainnetIcon, PolygonMainnetIcon } from "assets/icons";

const NetworkList = [
  //   {
  //     name: "Ethereum Mainnet",
  //     chain: "ETH",
  //     icon: EthereumMainnetIcon,
  //     rpc: [
  //       "https://api.mycryptoapi.com/eth",
  //       "https://cloudflare-eth.com",
  //       "https://rpc.flashbots.net",
  //       "https://eth-mainnet.gateway.pokt.network/v1/5f3453978e354ab992c4da79",
  //       "https://mainnet-nethermind.blockscout.com",
  //       "https://nodes.mewapi.io/rpc/eth",
  //       "https://main-rpc.linkpool.io",
  //       "https://mainnet.eth.cloud.ava.do",
  //       "https://ethereumnodelight.app.runonflux.io",
  //       "https://rpc.ankr.com/eth",
  //       "https://eth-rpc.gateway.pokt.network",
  //       "https://main-light.eth.linkpool.io",
  //       "https://eth-mainnet.public.blastapi.io",
  //       "http://18.211.207.34:8545",
  //       "https://eth-mainnet.nodereal.io/v1/1659dfb40aa24bbb8153a677b98064d7",
  //       "wss://eth-mainnet.nodereal.io/ws/v1/1659dfb40aa24bbb8153a677b98064d7",
  //       "https://api.bitstack.com/v1/wNFxbiJyQsSeLrX8RRCHi7NpRxrlErZk/DjShIqLishPCTB9HiMkPHXjUM9CNM9Na/ETH/mainnet",
  //       "https://eth-mainnet.unifra.io/v1/d157f0245608423091f5b4b9c8e2103e",
  //     ],
  //     faucets: [],
  //     nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
  //     infoURL: "https://ethereum.org",
  //     shortName: "eth",
  //     chainId: 1,
  //     networkId: 1,
  //     slip44: 60,
  //     ens: { registry: "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e" },
  //     explorers: [
  //       {
  //         name: "etherscan",
  //         url: "https://etherscan.io",
  //         standard: "EIP3091",
  //       },
  //     ],
  //     tvl: 51446750666.4789,
  //     chainSlug: "ethereum",
  //   },
  {
    name: "Görli",
    title: "Ethereum Testnet Görli",
    chain: "ETH",
    icon: EthereumMainnetIcon,
    rpc: [
      "https://rpc.goerli.mudit.blog",
      "https://eth-goerli.g.alchemy.com/v2/demo",
      "https://rpc.ankr.com/eth_goerli",
      "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
      "https://eth-goerli.public.blastapi.io",
    ],
    faucets: [
      "http://fauceth.komputing.org?chain=5&address=${ADDRESS}",
      "https://goerli-faucet.slock.it?address=${ADDRESS}",
      "https://faucet.goerli.mudit.blog",
    ],
    nativeCurrency: { name: "Görli Ether", symbol: "ETH", decimals: 18 },
    infoURL: "https://goerli.net/#about",
    shortName: "gor",
    chainId: 5,
    networkId: 5,
    ens: { registry: "0x112234455c3a32fd11230c42e7bccd4a84e02010" },
    explorers: [
      {
        name: "etherscan-goerli",
        url: "https://goerli.etherscan.io",
        standard: "EIP3091",
      },
    ],
  },
  {
    name: "Polygon Mainnet",
    chain: "Polygon",
    icon: PolygonMainnetIcon,
    rpc: [
      "https://polygon-rpc.com",
      "https://rpc-mainnet.matic.network",
      "https://matic-mainnet.chainstacklabs.com",
      "https://rpc-mainnet.maticvigil.com",
      "https://rpc-mainnet.matic.quiknode.pro",
      "https://matic-mainnet-full-rpc.bwarelabs.com",
      "https://matic-mainnet-archive-rpc.bwarelabs.com",
      "https://poly-rpc.gateway.pokt.network",
      "https://rpc.ankr.com/polygon",
      "https://polygon-mainnet.public.blastapi.io",
      "https://polygonapi.terminet.io/rpc",
    ],
    faucets: [],
    nativeCurrency: { name: "MATIC", symbol: "MATIC", decimals: 18 },
    infoURL: "https://polygon.technology/",
    shortName: "matic",
    chainId: 137,
    networkId: 137,
    slip44: 966,
    explorers: [
      {
        name: "polygonscan",
        url: "https://polygonscan.com",
        standard: "EIP3091",
      },
    ],
    tvl: 1638587533.7295463,
    chainSlug: "polygon",
  },
];

export default NetworkList;
